### ISSUE TITLE
When updating @tomic/react to 0.36: `registerOntologies is not a function`

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#727]
I just updated the React template to 0.36 and saw this error:

<img width="659" alt="Screenshot 2023-12-06 at 14 08 48" src="https://github.com/atomicdata-dev/atomic-server/assets/2183313/421eae29-ec1e-4bea-9aee-7701e971b13e">

The `registerOntologies` is imported from the parent index:

```
import { registerOntologies } from '../index.js';
```

Which in turn gets it from `ontologies.js`. Not sure why it can't find it.
